# Generated by Django 4.0 on 2024-11-22 00:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trade', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lIstingpost',
            name='title',
            field=models.CharField(max_length=200, verbose_name='商品名'),
        ),
    ]
